login_url = 'https://2020admission.giet.edu/admission/index.php?p=login'
registration_url = ''
# win_cred_file = 'E:\\Python_Workspace\\testing\\data3.txt'
win_cred_file = 'D:\\data01.txt'
linux_cred_file = ''
mock_data_file = 'D:\\mock_data.json'
# chrome_driver_path = 'E:\\Python_Workspace\\testing\\chromedriver.exe'
chrome_driver_path = 'C:\\Users\\PyDesk\\Downloads\\chromedriver_win32\\chromedriver.exe'
firefox_driver_path = '/usr/local/bin/geckodriver'
login_page_load_wait_duration = 5
post_login_req_wait = 10
email_issuers = ['gmail', 'yahoomail', 'outlook', 'rediffmail']
login_successful_div_element = 'left-panel'
login_failure_div_element = 'red-left'
login_failure_msg = 'Invalid Email or Password!'
log_file_path = 'D:\\automator.log'
breaker_file = 'D:\\break.txt'
apply_success = 'D:\\success.txt'
apply_failure = 'D:\\failure.txt'
